// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rowCorCpp
Rcpp::NumericVector rowCorCpp(IntegerVector idxX, IntegerVector idxY, Rcpp::NumericMatrix X, Rcpp::NumericMatrix Y);
RcppExport SEXP _find2Kat_rowCorCpp(SEXP idxXSEXP, SEXP idxYSEXP, SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type idxX(idxXSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type idxY(idxYSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(rowCorCpp(idxX, idxY, X, Y));
    return rcpp_result_gen;
END_RCPP
}
// tabulate2dCpp
IntegerMatrix tabulate2dCpp(IntegerVector& x, int& xmin, int& xmax, IntegerVector& y, int& ymin, int& ymax);
RcppExport SEXP _find2Kat_tabulate2dCpp(SEXP xSEXP, SEXP xminSEXP, SEXP xmaxSEXP, SEXP ySEXP, SEXP yminSEXP, SEXP ymaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int& >::type xmin(xminSEXP);
    Rcpp::traits::input_parameter< int& >::type xmax(xmaxSEXP);
    Rcpp::traits::input_parameter< IntegerVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int& >::type ymin(yminSEXP);
    Rcpp::traits::input_parameter< int& >::type ymax(ymaxSEXP);
    rcpp_result_gen = Rcpp::wrap(tabulate2dCpp(x, xmin, xmax, y, ymin, ymax));
    return rcpp_result_gen;
END_RCPP
}
// computeSparseRowVariances
Rcpp::NumericVector computeSparseRowVariances(IntegerVector j, NumericVector val, NumericVector rm, int n);
RcppExport SEXP _find2Kat_computeSparseRowVariances(SEXP jSEXP, SEXP valSEXP, SEXP rmSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type j(jSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type val(valSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rm(rmSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(computeSparseRowVariances(j, val, rm, n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_find2Kat_rowCorCpp", (DL_FUNC) &_find2Kat_rowCorCpp, 4},
    {"_find2Kat_tabulate2dCpp", (DL_FUNC) &_find2Kat_tabulate2dCpp, 6},
    {"_find2Kat_computeSparseRowVariances", (DL_FUNC) &_find2Kat_computeSparseRowVariances, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_find2Kat(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
